#!/bin/sh

# This script is used for view specified processes status in top

top -p $(pidof "$@" |sed s#\ #,#g) 2>/dev/null
if [ $? -ne 0 ]; then
     echo No processes with the specified name \(s\) were found
fi

